# Dockerfile for a FastAPI application-
# Dockerfile
FROM python:3.10-slim

# Avoid problems with pyc,
ENV PYTHONDONTWRITEBYTECODE=1
ENV PYTHONUNBUFFERED=1

# set working directory
WORKDIR /app

# Install system dependencies
COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# copy project  files
COPY . .

# expose the port the app runs on
EXPOSE 8000
# Execute the application
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]

